autoload_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Slide Presentation Admin"
admin.site.site_title = "Slide Presentation Admin Portal"
admin.site.index_title = "Welcome to Slide Presentation Portal"

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('homepage.urls')),
    #path('admin/', admin.site.urls),
    #url(r'^main/', include('main.urls'), namespace='Main'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.conf.urls import url
from homepage import views

urlpatterns = [
    url(r'^$', views.HomePageView.as_view()),
    url(r'^about/$', views.AboutPageView.as_view()),
    url(r'^request/$', views.RequestPageView.as_view()),
    url(r'submitted/$', views.SubmittedPageView.as_view()),

]

main/urls.py
# main/urls.py
from django.conf.urls import url
from main import views

app_name = 'main'

urlpatterns = [
    url("^$", views.LoginPageView.as_view()),
    url(r'^login/$', views.LoginPageView.as_view(), name='login'),
]

homepage/models.py
from django.db import models
from django.utils import timezone
import datetime
import os
import uuid
from django import forms

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.pptx', '.ppsx']
    if not ext in valid_extensions and ext is not None:
        raise forms.ValidationError(u'')
    return

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('slide/', filename)



class Slide(models.Model):

    id = models.AutoField(primary_key=True)
    #author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default="")
    department = models.CharField(max_length=200,default="")
    file = models.FileField(upload_to=get_file_path, validators=[validate_file_extension], blank=True, null=True)
    email = models.EmailField(default="")
    monitor = models.CharField(max_length=256, default="First Floor Lobby", choices=[('First Floor Lobby', 'First Floor Lobby'),('Second Floor Lobby','Second Floor Lobby'), ('Second Floor Office', 'Second Floor Office')])
    priority = models.CharField(max_length=2, default= 1,choices=[('1', '1'), ('2', '2'), ('3', '3'),('4','4'), ('5', '5'), ('6', '6'), ('7','7'),('8','8'), ('9', '9'),('10', '10')])
    start_date = models.DateField(default=datetime.date.today)
    end_date = models.DateField(default=datetime.date.today)
    status= models.CharField(max_length=20, default='pending', choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')])
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(default="")
    reject_info = models.CharField(max_length=200,blank=True, default="")

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.department


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    department = models.CharField(max_length=200)
    email = models.EmailField(max_length=70, null=True, blank=True, unique=True)
    role = models.CharField(max_length=2, default= '0')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.department

homepage/forms.py
from django import forms
from homepage.models import Slide
from django.contrib.admin import widgets


class SlideForm(forms.ModelForm):
    class Meta:
        model = Slide
        fields = ('department','email', 'monitor', 'start_date','end_date','file', 'description')
        start_date = forms.DateField(widget=forms.SelectDateWidget())
        end_date = forms.DateField(widget=forms.SelectDateWidget())

        def __init__(self, *args, **kwargs):
            super(SlideForm, self).__init__(*args, **kwargs)
            self.fields['date'].widget = widgets.AdminDateWidget()
            self.fields['start_date'].widget = widgets.AdminTimeWidget()
            self.fields['end_date'].widget = widgets.AdminTimeWidget()

homepage/views.py
from django.shortcuts import render
from homepage.forms import SlideForm
from django.views.generic import TemplateView
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib import messages
#views
class HomePageView(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'index.html', context=None)
class AboutPageView(TemplateView):
    template_name = "about.html"
class RequestPageView(TemplateView):
    template_name = "request.html"

    def get(self, request):
        form = SlideForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = SlideForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            form = SlideForm()
            email_address = 'jiangshanyigou@gmail.com'
            email = EmailMessage('New Slide Application', 'You have a new application', to=[email_address])
            email.send()
            return render(request, "submitted.html", locals())
        else:
            form = SlideForm()
            return render(request, self.template_name, {'form': form})
class SubmittedPageView(TemplateView):
    template_name = "submitted.html"

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class LoginPageView(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'main/login.html', context=None)

homepage/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body TEXT="DarkBlue">
    <center>
        <img src="https://www.duq.edu/assets/prebuilt/img/logo_school.png" class="img-fluid" alt="Duquesne University">
        <h2>To upload a slide request:</h2>
    </center>
    <div class="container">
    <div class="tab">

        <h3> 1. Make sure your slide is complete and all information on it is correct before uploading</h3>
        <h3> 2. Click on 'New Request' from the homepage</h3>
        <h3> 3. Fill out the form as accurately as possible</h3>
        <h3> 4. Note: the start and end dates are the dates the slide will be on display.</h3>
        <h3> 5. Upload file from computer and submit request</h3>
        <h3> 6. Montitor your email for updates</h3>
        </div>
    </div>
        <center><h4> All fields are subject to modification before approval.</h4></center>

    <br>
    <center>
        <a href="/autoload_system/"><button style="color:darkblue; height:50px; width:130px; background-color:white; border-color:darkred"><h3>Go Back Home</h3></button></a>
        <h3> Designed and created by Duquesne's Spring 2019 Software Engineering class.</h3>
    </center>
    </body>
<div class="container">

    <footer>
        <center><br><br></center>
    </footer>
         </div>
<style>
         footer {
        background-color:darkred;
    }
        .tab {
        margin-left:330px;
        }
</style>

</html>

homepage/templates/index.html
<!-- howdy/templates/index.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home</title>
    </head>
    <div class="container-fluid">
        <div class="container">
	<a href="http://slideshow.ml/autoload_system/admin/"><button style="color:darkblue; height:37px; width:100px; background-color:white; border-color:darkred; margin-left:1100px">Admin Login</button></a>

        </div>
        </div>
    <center>
        <img src="https://www.duq.edu/assets/prebuilt/img/logo_school.png" class="img-fluid" alt="Duquesne University">
    </center>

    <body TEXT="DarkBlue">
    <div class="container">
        <img src="https://www.lg.com/in/images/display/md05845269/gallery/small02.jpg?fbclid=IwAR09OHomb0hSvXMAmmd1HU4sqA4gfVw90BU-_W_AUMYswRObRxjFVE59iV8" height="350" width="520" class="leftimage" alt="Landscape">
        <img src="https://images-na.ssl-images-amazon.com/images/I/31z8dgOCWyL._SY355_.jpg?fbclid=IwAR1clolfOH5ew5u713CWucE74wVSRmOQ4XTspfivd9514VZ0UIpPdSyxT_A" height="300" width="375" class="rightimage" alt="Portrait">

	</div>
    <center>
        <div class="container-fluid">
        <h1>College Hall Slide Presentation Request Page</h1>
               <div class="container">
            <div class="left"><h3>Lobby Monitors</h3></div>
            <div class="right"><h3>Office Monitor</h3></div>
        <h2>First and Second Floor Lobbies</h2>
        <h2>Second Floor Office</h2>


            <div class="btn-group" role="group" aria-label="Basic example">
                <br><br>

  <a href="/autoload_system/about/"><button style="color:darkblue; height:65px; width:130px; background-color:white; border-color:darkred" ><h2>About</h2></button></a>
                <br><br>
                <a href="/autoload_system/request/"><button style="color:darkblue; height:80px; width:130px; background-color:white; border-color:darkred"><h2>New Request</h2></button></a>
</div>
</div>
        </div>
     </center>

    </body>
    <br><br><br><br><br><br><br>
     <div class="container">
    <footer>
        <center><br><br></center>
    </footer>
         </div>
    <style>
    footer {
        background-color:darkred;
    }
.container {
  position: relative;
  text-align: center;
  color: darkblue;
}
.left {
  position: absolute;
  top: 30px;
  left: 200px;
}
.right {
  position: absolute;
  top: 30px;
  right: 200px;
}
.leftimage {
    position: absolute;
    top: 140px;
    left: 5px;
}
.rightimage {
    position: absolute;
    top: 175px;
    right: 80px;
}
</style>

</html>

homepage/templates/request.html
<!-- howdy/templates/index.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Request</title>
    </head>
    <style>
         footer {
        background-color:darkred;
    }
    .ui-datepicker {
   background: #c4dce8;
   border: 1px solid #f7f7f7;
   color: #447e9b;
    }
    </style>
    <center>
        <img src="https://www.duq.edu/assets/prebuilt/img/logo_school.png" class="img-fluid" alt="Duquesne University">

    </center>
    <body TEXT="DarkBlue">
    <center>
        <div class="container-fluid">
        <h1>Submit New Slide Request Here!</h1>
            <script src="//code.jquery.com/jquery-1.10.2.js"></script>
            <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
            <script>
                $(document).ready(function(){
                    $( "#id_start_date" ).datepicker({ dateFormat: 'yy-mm-dd' });
                    $( "#id_end_date" ).datepicker({ dateFormat: 'yy-mm-dd' });
                    $("#id_start_date").blur(function(){
                        val = $(this).val();
                        val1 = Date.parse(val);
                        if (isNaN(val1)==true && val!==''){
                            alert("The start_date is error");
                            document.getElementById('id_start_date').value = "";
                        }
                        else{
                           console.log(val1);
                        }
                    });
                    $("#id_end_date").blur(function(){
                        val = $(this).val();
                        val1 = Date.parse(val);
                        if (isNaN(val1)==true && val!==''){
                            alert("The end_date is error");
                            document.getElementById('id_end_date').value = "";

                        }
                        else{
                           console.log(val1);
                        }
                    });

                    $("#id_file").blur(function () {
                        val = $(this).val();
                        if(val && !val.match(/\.(ppt|pptx|ppsx)$/i)) {
                            $("#id_error").show();
                            $("#id_file").val('');
                            $("#btnSubmit").attr('disabled', true);
                        }
                        else {
                            $("#id_error").hide();
                            $("#btnSubmit").attr('disabled', false);
                        }

                    })
                });

{#            {% if messages %}#}
{#                {% for message in messages %}#}
{#                    alert(message);#}
{#                {% endfor %}#}
{#            {% endif %}#}

            </script>

<!--           <form action="/action_page.php">
  <script>

 function set(){
    var el = document.getElementById("lobbies");
    if(el.checked)
      document.getElementById("1f").disabled = false;
    else
     document.getElementById("1f").disabled = true;
        if(el.checked)
      document.getElementById("2f").disabled = false;
    else
     document.getElementById("2f").disabled = true;
  }
</script>


<div><input type="radio" name="o1" id="lobbies" onchange="set();"/>Lobbies</div>
<div id="yesFries"><input type="checkbox" name="e1" id="1f" disabled="disabled"/>First Floor Lobby<br>
<input type="checkbox" name="e1" id="2f" disabled="disabled"/>Second Floor Lobby</div>

<div><input type="radio" name="o1" id="office" onchange="set();"/>Second Floor Office</div>
</form>

        <form action="/action_page.php">
        Email:<br>
        <input type="text" name="email" >
        <br>
        Name/Department:<br>
        <input type="text" name="name" >
        <br>
            Description:<br>
            <input type="text" name="description" >
            <br><br>

            <label for="start">Start date:</label>

<input type="date" id="start" name="start"
       min="2018-01-01" max="3000-12-31">

            <label for="start">End Date:</label>

<input type="date" id="start" name="end"
       min="2018-01-01" max="3000-12-31">
            </form>
           <form action="contact.php"
enctype="multipart/form-data" method="post" name="EmailTestData">

<p>
Choose File From Computer:
<input type="file" name="datafile" size="40" style="color:darkred">
</p>
                 <input type="submit" value="Submit" style="color:darkblue; height:25px; width:110px; background-color:white; border-color:darkred">
            <br>
             </form>

-->
<!--<p>If you click the "Submit" button, the form-data will be sent to a page called "/action_page.php".</p>-->
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p}}
                <button id="btnSubmit" type="submit">submit</button>
                <div id = "id_error" style="display:none;" ><p style="color:red;">The file type is not accepted, please upload ppsx file.</p></div>
            </form>
            <br><br>
            <a href="/autoload_system" class="w3-button w3-border w3-xlarge"><button class="w3-button w3-border w3-xlarge" style="color:darkblue; height:25px; width:110px; background-color:white; border-color:darkred">Go Back Home</button></a>
        </div>
    </center>
    </body>
<br><br>
<div class="container">
    <footer>
        <center><br><br></center>
    </footer>
         </div>

</html>

homepage/templates/submitted.html
<!-- howdy/templates/index.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Submitted</title>
    </head>
    <center>
     <img src="https://www.duq.edu/assets/prebuilt/img/logo_school.png" class="img-fluid" alt="Duquesne University">
    </center>
    <body TEXT="DarkBlue">
    <center>
	<h1>Your Submission Has Been Sent!</h1>
	<h2>Montior Your Email For Updates</h2>
        <a href="/autoload_system"><button>Go Back Home</button></a>

        </center>
    </body>

</html>

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<h1>hello</h1>
</body>
</html>

main/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<h1>login</h1>
</body>
</html>